### ISSUE TITLE
Omit Signature Files From Dependent JARs 

### ISSUE THREAD

**Issue by arielvalentin** [colinsurprenant/redstorm#108]
I am trying to include a JAR that was signed by the author, however the redstorm jar task does not exclude [signature files|http://docs.oracle.com/javase/6/docs/technotes/guides/jar/jar.html#Signed%20JAR%20File], which results in an SecurityException:   

``` xml```
<?xml version="1.0"?>
<ivy-module version="2.0" xmlns:m="http://ant.apache.org/ivy/maven">
  <info organisation="redstorm" module="topology-deps"/>
  <dependencies>
    <dependency org="org.jruby" name="jruby-core" rev="1.7.11" conf="default" transitive="true"/>
    <dependency org="org.jruby" name="jruby-stdlib" rev="1.7.11" conf="default" transitive="true"/>

    
    
    <dependency org="com.github.jnr" name="jffi" rev="1.2.7" conf="default" transitive="true">
      <artifact name="jffi" type="jar" />
      <artifact name="jffi" type="jar" m:classifier="native"/>
    </dependency>

    <dependency org="net.sf.saxon" name="Saxon-HE" rev="9.4.0-8"/>
  </dependencies>
</ivy-module>
```

``` bash```
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:286)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:239)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:274)
        at java.util.jar.JarVerifier.update(JarVerifier.java:228)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:348)
        at java.util.jar.JarFile.getInputStream(JarFile.java:415)
        at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:775)
        at sun.misc.Resource.cachedInputStream(Resource.java:77)
        at sun.misc.Resource.getByteBuffer(Resource.java:160)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:436)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by colinsurprenant** [comment]
Ok, thanks for reporting and pointing to the relevant docs. I guess it should be as easy as excluding those files when re-jarring, will test.

**Comment by rtyler** [comment]
FWIW, I hit this with the [jruby-gradle/jruby-gradle-storm-plugin](/jruby-gradle/jruby-gradle-storm-plugin) work that I've been doing, it's pretty simple in Gradle to handle this, see [this shadowjar configuration](https://github.com/jruby-gradle/jruby-gradle-storm-plugin/blob/master/src/main/groovy/com/github/jrubygradle/storm/JRubyStormPlugin.groovy#L36).

The jruby-gradle-storm-plugin does depend on a divergent [redstorm](/jruby-gradle/redstorm) library though
