### ISSUE TITLE
java.io.NotSerializableException when serialize Hash between tasks

### ISSUE THREAD

**Issue by stonegao** [colinsurprenant/redstorm#8]
One of the fields in our spout is Hash, but it seems that JRuby's RubyHashEntry is not serializable.  

<pre>
1461 [Thread-49] ERROR backtype.storm.util  - Async loop died!
java.io.NotSerializableException: org.jruby.RubyHash$RubyHashEntry
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1164)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:330)
        at backtype.storm.serialization.JavaSerialization.serialize(JavaSerialization.java:20)
        at backtype.storm.serialization.JavaSerialization.serialize(JavaSerialization.java:14)
        at backtype.storm.serialization.FieldSerialization.serialize(FieldSerialization.java:26)
        at backtype.storm.serialization.ValuesSerializer.serializeInto(ValuesSerializer.java:50)
        at backtype.storm.serialization.TupleSerializer.serialize(TupleSerializer.java:31)
        at backtype.storm.daemon.worker$fn__3076$exec_fn__860__auto____3077$fn__3137$fn__3138.invoke(worker.clj:189)
        at backtype.storm.daemon.worker$fn__3076$exec_fn__860__auto____3077$fn__3137.invoke(worker.clj:184)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.AFn.applyTo(AFn.java:151)
        at clojure.core$apply.invoke(core.clj:540)
        at backtype.storm.util$async_loop$fn__445.invoke(util.clj:215)
        at clojure.lang.AFn.run(AFn.java:24)
        at java.lang.Thread.run(Thread.java:680)
</pre>

**Comment by colinsurprenant** [comment]
right. I wonder how to approach this problem with Ruby objects serialization. Maybe custom serializers? 

In the mean time I suggest 3 possible solutions:

1- just directly use a Java Hashmap instead of a Ruby Hash or

2- convert between a Java Hashmap and a Ruby Hash using (this will not support nested hash...)
 javaHashMap = HashMap.new(rubyHash)
 rubyHash = Hash[*javaHashMap.to_a.flatten]

3- serialize the Ruby hash yourself to json 

Is your hash big? You'll have to test for the performance hit, Let me know.

**Comment by stonegao** [comment]
Thanks for your suggestions, the use case is the spout get json serialized data from queue, then decode to ruby hash, the size of hashes when serialized in json used in our topology range from 10KB to 100KB, so it's petty big for most of them. They are also nested, according to your suggestions, it seems only approach **3 serialize the Ruby hash yourself to json**  or **custom serializers** can be used

**Comment by colinsurprenant** [comment]
I think passing your hash serialized as a json string should be an acceptable solution without much performance penalty. In the end serialization has to be done one way or another, and if your hash is already serialized as a string, it should be pretty mush a passthrough.

**Comment by colinsurprenant** [comment]
@stonegao did you have any success with this?

**Comment by stonegao** [comment]
Currently I am using the json serialization approach you suggested. I have no idea what the performance penalty is.

**Comment by headius** [comment]
We should probably implement serialization on the JRuby core classes to always use Ruby Marshal logic rather than default JVM serialization logic. It will probably be faster, and there's various issues attempting to serialize a JRuby object across runtimes.

**Comment by headius** [comment]
Actually now that I think about it, we probably would want to make Java serialization on a Ruby Hash coerce all contents. There's no clean/safe way to deserialize a Ruby object with Java serialization because the construction of the object requires a JRuby instance to be passed in (and none is available when Java serialization constructs the "empty" object).

Is there an example use case I can run to trigger this error?

**Comment by sam** [comment]
@headius Being able to serial Strings, Numerics, Arrays and Hashes by default would be nice. Basically the old rule about Session storage (since that's my use-case): Primitives, Arrays and Hashes only. Don't store complex objects in Session so you don't have to worry about custom serialization/marshalling.

Honestly it's a nice-to-have though. Writing a recursive (Hash|Array)#to_serializable is easy enough and on de-serialization I don't care if the Enumerables I'm working with are java.util.HashMaps instead of Ruby Hashes.

Same effect for a consumer/developer as calling to_json myself, except deserialization doesn't carry the performance penalty of running through a JSON parser unnecessarily.

Just a brain-dump I guess. I don't pretend to know if implementing coercion for Hashes/Arrays in JRuby would have some undesired side-effects that make the idea infeasible.
